# Generated by Django 2.0.7 on 2019-02-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is my 1st model'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='100'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='This is cool'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='Basketball'),
        ),
    ]
